
url:
  login_url: "https://ecommerce-playground.lambdatest.io/index.php?route=account/login"

credentials:
  valid_username: "karim.belboukhari1@yopmail.com"
  valid_password: "Test@1234$"
  invalid_username: "invalid_username"
  invalid_password: "invalid_password"